# Site settings
title: Health Pedia
name: Health Pedia
description: "eating healthy,fit women,fitness,fitness tips,health and fitness,health and fitness blogs,healthiest foods,healthy diet,healthy eating,healthy food,healthy meals"
tagline: "health department"
keywords: "eating healthy,fit women,fitness,fitness tips,health and fitness,health and fitness blogs,healthiest foods,healthy diet,healthy eating,healthy food,healthy meals,healthy recipes"
baseurl: "" 
url: https://healthpedia.co.uk
logo: '/assets/logo.png'
# User settings
username: Health Pedia
user_description: Say good bye to drug addiction, stop drug misuse,free drug and alcohol treatment home,no addiction no alcoholic, goodbye letter to drugs,addiction and alcoholic
user_title: Health Department
email: healthpedia4u@gmail.com
twitter_username: healthpedia
github_username:  healthpedia
gplus_username:  healthpedia
disqus_username: healthpedia
paginate: 6
paginate_path: /page/:num/
infinite_scroll: false
gems: [jekyll-paginate]
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Categories
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
